### ISSUE TITLE
Should filter file be added to config?

### ISSUE THREAD

**Issue by ChuckHL** [Andrwe/privoxy-blocklist#10]
I'm new at your app and I like it can convert adblock lists to privoxy lists. I noticed that when I ran your script, it creates an .action and a .filter file for each list. I noticed that for each .action file, a new entry is created at the config file. (i.e. actionsfile fanboy-ultimate.script.action) but the same cannot be said about the .filter file. No entry regarding the filterfile is created within the config file. Should an entry file be created for the config file? If not, how is the .filter file being used?

Thanks in advance.
Regards

**Comment by Andrwe** [comment]
Every .filter file is registered with the directive `filterfile` within the config.

I couldn't reproduce the behaviour.
If it still exists for you, please reopen the issue with a sample URL to allow reproduction of the behaviour.
