### ISSUE TITLE
$PRIVOXY_CONF isn't set

### ISSUE THREAD

**Issue by DominicTannert** [Andrwe/privoxy-blocklist#12]
I have been following the instructions for setting up Privoxy on Archlinux with adblocker.
While running the privoxy-blocklist.sh I receive the following error:

`$PRIVOXY_CONF isn't set please either provice a valid initscript config or set it in /etc/conf.d/privoxy-blacklist .`

Any idea what is going on?

**Comment by lls-hcr** [comment]
The first time you run the script, a configuration file named "privoxy-blacklist" is created in /etc/conf.d/privoxy-blacklist, as mentioned in the message. Open the file and adjust the configuration as needed, then re-run the script to download and install the blacklists.

**Comment by Andrwe** [comment]
The message indicates that your system does not provide an environment file which is sourced by an init-script in the path defined by `INIT_CONF` in `/etc/conf.d/privoxy-blacklist`.

This will happen for all systems running systemd or `INIT_CONF` points to the wrong file.

I'll check if I can get the required information automatically.

**Comment by Andrwe** [comment]
Will be solved with #26
