### ISSUE TITLE
Is this project/repo dead?

### ISSUE THREAD

**Issue by Pandoriaantje** [Andrwe/privoxy-blocklist#13]
I've just cloned this wonderful project, and already had to fix 3 bugs/coding errors, found in the issues section. it seems that any pull requests for bug fixes are ignored. So is this project dead? wouldn't it be better if someone took over the project?

**Comment by Andrwe** [comment]
Thank you for your support with https://github.com/Andrwe/privoxy-blocklist/pull/14.
For a long time I did not use this project anymore and had less time to maintain it.

As I'll start using it again I'll invest more time, fix bugs and modernize the whole system.

**Comment by Pandoriaantje** [comment]
Great to hear its back alive. I take no credit for the proposed fixes, and just gathered them from the issue tracker, and integrated them all in my fork (also fixed the easylist link). So all credit goes to the kind people who proposed these fixes.
