### ISSUE TITLE
Add a Git tag with the script version

### ISSUE THREAD

**Issue by sorin-ionescu** [Andrwe/privoxy-blocklist#2]
This tag is necessary for package managers.

**Comment by Andrwe** [comment]
FYI: I prepared the repository and release process to provide a version with the next release (0.4.0).

**Comment by Andrwe** [comment]
First version [0.4.0](https://github.com/Andrwe/privoxy-blocklist/releases/tag/0.4.0) was released and follow-up updates will create new versions.
