### ISSUE TITLE
What does it modify?

### ISSUE THREAD

**Issue by gerroon** [Andrwe/privoxy-blocklist#5]
Hi

I came across your script. This looks good except that I do not understand which privoxy files it changes? Is this a separate daemon? Does it add to privoxy files?

It would be nice if you clarify in the help.

thanks

**Comment by o-jasper** [comment]
Would prefer to be told where to put the files and not run it as root.

**Comment by Andrwe** [comment]
The script downloads AdBlock Plus filter files and generates dedicated privoxy action and filter files from those.
Then it installs the generated files into the privoxy configuration file.

The script is intended to run as cron to periodically generate up-to-date filter files.
