### ISSUE TITLE
HTTPS Inspection

### ISSUE THREAD

**Issue by ak2766** [Andrwe/privoxy-blocklist#54]
I guess this goes without saying but I'd imagine it best to cover it in the README that one needs to build `privoxy` with `FEATURE_HTTPS_INSPECTION`.

**Comment by Andrwe** [comment]
`privoxy-blocklist' does not need Privoxy to be build with `FEATURE_HTTPS_INSPECTION` necessarily as it only generates a configuration for Privoxy.
The feature of content filtering provided by Privoxy needs this compiler flag.

Still I'll add a hint about this feature dependency to the README, thanks for the hint.
