### ISSUE TITLE
filterfile: command not found

### ISSUE THREAD

**Issue by bonanza123** [Andrwe/privoxy-blocklist#6]
I'm receiving this error when running the code. But it still seems to work:

> root@OpenWrt:/etc/privoxy# ./privoxy-blocklist.sh 
> Processing https://easylist-downloads.adblockplus.org/malwaredomains_full.txt ...
> 
> Downloading https://easylist-downloads.adblockplus.org/malwaredomains_full.txt ...
> .. downloading done.
> ./privoxy-blocklist.sh: line 154: filterfile: command not found
> ... https://easylist-downloads.adblockplus.org/malwaredomains_full.txt installed successfully.

**Comment by archeando** [comment]
Line 154 has an error, change it to:
    if [ "$(grep $(basename ${filterfile}) ${PRIVOXY_CONF})" == "" ]

**Comment by Andrwe** [comment]
solved by https://github.com/Andrwe/privoxy-blocklist/pull/14
