### ISSUE TITLE
wrong host patterns

### ISSUE THREAD

**Issue by chew-z** [Andrwe/privoxy-blocklist#7]
Seems like Privoxy can't understand host patterns containg backslash (unlike in filter regex). You are using host patterns like '.apple\.com' in action file which is ignored and should be '.apple.com' instead. For that reason blocking doesn't catch right doimains most of the time.

http://www.privoxy.org/user-manual/actions-file.html#HOST-PATTERN

**Comment by Andrwe** [comment]
Thanks for reporting this issue. (https://github.com/Andrwe/privoxy-blocklist/actions/runs/7367794392/job/20051410065?pr=34)
I can reproduce it and will fix it soon.
