### ISSUE TITLE
sed complain about [[:space:]], not [:space:]

### ISSUE THREAD

**Issue by szorfein** [Andrwe/privoxy-blocklist#9]
hi, i try debuggin your script because it seem don't work on recent version of bash...look this part.
( this is just a minimal version of your script for debuggin )

    #! /bin/bash

    TMPDIR="/tmp/privoxy"
    URLS=  ("https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_thirdparty.txt")

    if [[ ! -d $TMPDIR ]] ; then
        echo "mkdir $TMPDIR"
        install -d -m700 $TMPDIR
    fi

    for url in ${URLS[@]}
    do
        echo "Processing ${url} ...\n" || exit 0
        file=${TMPDIR}/$(basename ${url})
        actionfile=${file%\.*}.script.action
        filterfile=${file%\.*}.script.filter
        list=$(basename ${file%\.*})

        echo "Downloading ${url} ..." || exit 0
        wget -t 3 -O $file $url
        echo ".. downloading done." || exit 0
    
        echo "Creating actionfile for $list" || exit 1
        echo -e "{ +block{${list}} }" > "${actionfile}"
        sed '/^!.*/d;1,1 d;/^@@.*/d;/\$.*/d;/#/d;s/\./\\./g;s|?|\\?|g;s/\*/.*/g;s/(/\\(/g;s/)/\\)/g;s/\[/\\[/g;s/\]/\\]/g;s/\^/[\/\&:\?=_]/g;s/^||/\./g;s/^|/^/g;s/|$/\$/g;/|/d' ${file} >> ${actionfile}
        echo "actionfile -> $actionfile done"

        echo "Creating filterfile for $list..." || exit 1
        echo "FILTER: ${list} Tag filter of ${list}" > "${filterfile}"

       # this bug here <This sed command doesn't work>
       sed '/^#/!d;s/^##//g;s/^#\(.*\)\[.*\]\[.*\]*/s@<([a-zA-Z0-9]+)\\s+.*id=.?\1.*>.*<\/\\1>@@g/g;s/^#\(.*\)/s@<([a-zA-Z0-9]+)\\s+.*id=.?\1.*>.*<\/\\1>@@g/g;s/^\.\(.*\)/s@<([a-zA-Z0-9]+)\\s+.*class=.?\1.*>.*<\/\\1>@@g/g;s/^a\[\(.*\)\]/s@<a.*\1.*>.*<\/a>@@g/g;s/^\([a-zA-Z0-9]*\)\.\(.*\)\[.*\]\[.*\]*/s@<\1.*class=.?\2.*>.*<\/\1>@@g/g;s/^\([a-zA-Z0-9]*\)#\(.*\):.*[:[^:]]*[^:]*/s@<\1.*id=.?\2.*>.*<\/\1>@@g/g;s/^\([a-zA-Z0-9]*\)#\(.*\)/s@<\1.*id=.?\2.*>.*<\/\1>@@g/g;s/^\[\([a-zA-Z]*\).=\(.*\)\]/s@\1^=\2>@@g/g;s/\^/[\/\&:\?=_]/g;s/\.\([a-zA-Z0-9]\)/\\.\1/g' ${file} >> ${filterfile}

        echo "{ +filter{${list}} }" >> "${actionfile}"
        echo "*" >> ${actionfile}
        echo "... filterfile added ..." || exit 1

    done

The error -> sed: character class syntax is [[:space:]], not [:space:]

**Comment by Bernd-Osterhage** [comment]
It seems that there is an escape char in front of the first ":" missing!
Original part: `*[:[^:]]*[^:]*`
Changed part: `*[\:[^:]]*[^:]*`

**Comment by szorfein** [comment]
thanks, it seem to work.

**Comment by IlVerz** [comment]
It works! Thans 👍

**Comment by bastiandoetsch** [comment]
Works for me, too.

**Comment by mkaand** [comment]
Thanks man. I recently upgraded my server from Ubuntu 16.04 to 18.04 and I start receiving errors for this script (same error) I fixed with your solution. I guess bash version changed after upgrade. That's why script failed.

**Comment by Andrwe** [comment]
merged into master with https://github.com/Andrwe/privoxy-blocklist/pull/14
